### ISSUE TITLE
Rolling log files split between processes

### ISSUE THREAD

**Issue by ivelin** [ambianic/ambianic-edge#170]
It appears that when logs roll after reaching size limit, some processes write to the new log and others to the older log files.

**Comment by muka** [comment]
Hi,
seems log rotation does not play nice with multithreading, see
https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes

`Although logging is thread-safe, and logging to a single file from multiple threads in a single process is supported, logging to a single file from multiple processes is not supported, because there is no standard way to serialize access to a single file across multiple processes in Python.`

A good replacement solution could be the [concurrent-log-handler](https://github.com/Preston-Landers/concurrent-log-handler) package.

**Comment by ivelin** [comment]
That makes sense. The gstreamer pipeline elements run in separate processes.
